"""Known-answer fixtures for the anima_v3 harness — the G-3 estimator gate.

@canonical-ok — the `v3` here is not a version suffix on this file: it mirrors the
canonical module under test, `tool/anima_v3.py`, whose name is the campaign's own
canonical identity (repo `anima-v3`, the clean-slate successor campaign to `anima`).
Renaming this to drop `v3` would DEsynchronize it from the module it tests.

This is not a unit test in the hygiene sense; it is a POSITIVE CONTROL on the
measuring instrument, pre-registered as falsifier G-3 of H_001. Its job is to
fail loudly when an estimator has gone blind, because every downstream verdict
is only as trustworthy as the estimator that produced it (salvage L6 — the v1
campaign's measurements, not its ideas, are what buried it).

Each case has a closed-form answer known BEFORE the estimator runs. No fitting,
no fixture whose expected value was read off the implementation's output.

Run: python3 tool/test_anima_v3.py   (exit 0 = all pass, 1 = an estimator is blind)
"""

from __future__ import annotations

import math
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

from anima_v3 import (
    ablation_delta,
    ablation_fraction,
    bits_per_byte,
    effective_rank,
    gram_matrix,
    participation_ratio,
    singular_values,
    stable_rank,
)

_results: list = []


def check(name: str, got: float, want: float, tol: float = 1e-6) -> None:
    ok = abs(got - want) <= tol
    _results.append(ok)
    print(f"{'PASS' if ok else 'FAIL'}  {name:<52} got={got:.6f} want={want:.6f} tol={tol:g}")


def check_between(name: str, got: float, low: float, high: float) -> None:
    ok = low < got < high
    _results.append(ok)
    print(f"{'PASS' if ok else 'FAIL'}  {name:<52} got={got:.6f} want=({low},{high})")


def check_raises(name: str, fn) -> None:
    try:
        fn()
        ok = False
        detail = "no exception"
    except ValueError:
        ok = True
        detail = "ValueError"
    _results.append(ok)
    print(f"{'PASS' if ok else 'FAIL'}  {name:<52} got={detail} want=ValueError")


def rank_k_fixture(k: int, width: int, energy: float = 1.0) -> list:
    """Observations spanning exactly k orthogonal directions with EQUAL energy.

    Closed-form: participation_ratio == effective_rank == stable_rank == k.
    """
    if k > width:
        raise ValueError("k must be <= width")
    rows = []
    for i in range(k):
        pos = [0.0] * width
        neg = [0.0] * width
        pos[i] = energy
        neg[i] = -energy
        rows.append(pos)
        rows.append(neg)
    return rows


def boundary_delta_rank1(n_probes: int, length: int) -> list:
    """A rank-1 boundary-delta matrix B: every probe's boundary change is the
    SAME pattern scaled — i.e. all codec drift generated by one merge family.

    This is the F1 analogue of v1's death mode (a seam whose only learned bit is
    its own existence). Closed-form: PR == 1 exactly.
    """
    pattern = [1.0 if j % 3 == 0 else 0.0 for j in range(length)]
    return [[(i + 1) * v for v in pattern] for i in range(n_probes)]


def main() -> int:
    print("=== L1 estimators — participation_ratio (pre-registered gate) ===")
    # Rank-1 seam: the exact shape that killed v1. PR must read 1.0.
    sv = singular_values(boundary_delta_rank1(8, 12))
    check("rank-1 boundary-delta B -> PR", participation_ratio(sv), 1.0, tol=0.1)
    check("rank-1 boundary-delta B -> effective_rank", effective_rank(sv), 1.0, tol=0.1)
    check("rank-1 boundary-delta B -> stable_rank", stable_rank(sv), 1.0, tol=0.1)

    # Rank-k fixtures: G-3 requires k within 20%.
    for k in (2, 3, 4, 5):
        sv = singular_values(rank_k_fixture(k, width=6))
        check(f"rank-{k} equal-energy fixture -> PR", participation_ratio(sv), float(k), tol=0.2 * k)
        check(f"rank-{k} equal-energy fixture -> effective_rank", effective_rank(sv), float(k), tol=0.2 * k)

    # A seam that never varies is rank-0 variation, not rank-1.
    sv = singular_values([[5.0, 7.0]] * 4)
    check("constant seam -> PR", participation_ratio(sv), 0.0)
    check("constant seam -> effective_rank", effective_rank(sv), 0.0)

    # Dominant + weak direction must land strictly between 1 and 2: a seam that
    # merely twitches along a second direction must NOT clear a rank-2 gate.
    sv = singular_values([[1.0, 0.01], [-1.0, -0.01], [0.0, 0.01], [0.0, -0.01]])
    check_between("dominant+weak dirs -> PR in (1,2)", participation_ratio(sv), 1.0, 2.0)
    check_between("dominant+weak dirs -> effective_rank in (1,2)", effective_rank(sv), 1.0, 2.0)

    # PR weights by energy, so a weak second direction reads LOWER on PR than on
    # the entropy estimator. The gate must be quoted on PR, never whichever
    # estimator happens to clear the threshold.
    sv = singular_values([[1.0, 0.2], [-1.0, -0.2], [0.0, 0.2], [0.0, -0.2]])
    pr, er = participation_ratio(sv), effective_rank(sv)
    ok = pr < er
    _results.append(ok)
    print(f"{'PASS' if ok else 'FAIL'}  {'PR is stricter than erank on weak 2nd dir':<52} PR={pr:.4f} < erank={er:.4f}")

    print("\n=== bits-per-byte — codec-invariant unit (salvage L6) ===")
    check("bpb identity: ln2 nats/token, 1 token/byte", bits_per_byte(math.log(2), 100, 100), 1.0)
    # The whole point: a coarser codec halves tokens and doubles CE/token while
    # predicting identically. bpb must not move.
    check("bpb invariance: coarse codec, same prediction", bits_per_byte(2 * math.log(2), 50, 100), 1.0)
    check("bpb invariance: fine codec, same prediction", bits_per_byte(0.5 * math.log(2), 200, 100), 1.0)
    check("bpb scales with real prediction gain", bits_per_byte(0.5 * math.log(2), 100, 100), 0.5)

    print("\n=== L2 ablation ===")
    # v1's OMEGA moved 0.0009 nats — the campaign's reference signature of decoration.
    check("ablation_delta = v1 OMEGA decoration floor", ablation_delta(2.0009, 2.0), 0.0009, tol=1e-9)
    check("ablation_fraction: half the headroom to floor", ablation_fraction(2.5, 2.0, 3.0), 0.5)
    check("ablation_fraction: channel carries everything", ablation_fraction(3.0, 2.0, 3.0), 1.0)
    check("ablation_fraction: channel carries nothing", ablation_fraction(2.0, 2.0, 3.0), 0.0)

    print("\n=== guards — a broken control must RAISE, never return a number ===")
    check_raises("floor <= intact CE (broken control)", lambda: ablation_fraction(2.5, 2.0, 1.0))
    check_raises("ragged observation vectors", lambda: gram_matrix([[1.0, 2.0], [3.0]]))
    check_raises("empty observation set", lambda: gram_matrix([]))
    check_raises("zero-width observations", lambda: gram_matrix([[], []]))
    check_raises("bpb with zero bytes", lambda: bits_per_byte(1.0, 10, 0))
    check_raises("bpb with zero tokens", lambda: bits_per_byte(1.0, 0, 10))

    n_pass = sum(_results)
    n_total = len(_results)
    print(f"\n{n_pass}/{n_total} PASS")
    if n_pass != n_total:
        print("G-3 TRIGGERED — an estimator is blind; no downstream verdict is interpretable.")
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
